spring.application.name=ecommerce
server.port=2424
# spring.web.resources.add-mappings=false
spring.datasource.url=jdbc:mysql://localhost:3306/eccomercedp
# spring.jpa.show-sql=true
spring.datasource.username=root
spring.datasource.password=Hari@2006
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
secreteJwtString = Hari2726hv